In [4]:
from pathlib import Path

from zero_data.io_list.readers.marpower import MarpowerReader

df = (
    MarpowerReader()
    .read_io_list([Path("../io_lists/52422003_3211_PMS IO-List R2.6.xlsx")])
    .io_list
)
df

shape: (10_527, 13)
┌────────┬────────────┬──────────┬────────────┬───┬───────────┬───────────┬────────────┬───────────┐
│ device ┆ tag        ┆ yard_tag ┆ target_typ ┆ … ┆ precision ┆ data_type ┆ mqtt_topic ┆ mqtt_json │
│ ---    ┆ ---        ┆ ---      ┆ e          ┆   ┆ ---       ┆ ---       ┆ ---        ┆ _path     │
│ str    ┆ str        ┆ str      ┆ ---        ┆   ┆ null      ┆ str       ┆ str        ┆ ---       │
│        ┆            ┆          ┆ str        ┆   ┆           ┆           ┆            ┆ str       │
╞════════╪════════════╪══════════╪════════════╪═══╪═══════════╪═══════════╪════════════╪═══════════╡
│ KEB6   ┆ GFDEnabled ┆ null     ┆ Bool       ┆ … ┆ null      ┆ BOOLEAN   ┆ 450000 DC  ┆ $.MTS PMS │
│        ┆            ┆          ┆            ┆   ┆           ┆           ┆ DISTRIBUTI ┆ KEB6      │
│        ┆            ┆          ┆            ┆   ┆           ┆           ┆ ON         ┆ Ground    │
│        ┆            ┆          ┆            ┆   ┆           ┆           ┆            ┆ Fault Di… │
│ KEB6   ┆ FieldVolta ┆ null     ┆ Bool       ┆ … ┆ null      ┆ BOOLEAN   ┆ 450000 DC  ┆ $.MTS PMS │
│        ┆ geAvailabl ┆          ┆            ┆   ┆           ┆           ┆ DISTRIBUTI ┆ KEB6      │
│        ┆ e          ┆          ┆            ┆   ┆           ┆           ┆ ON         ┆ Voltage   │
│        ┆            ┆          ┆            ┆   ┆           ┆           ┆            ┆ Availab…  │
│ KEB6   ┆ PA24V      ┆ null     ┆ Bool       ┆ … ┆ null      ┆ BOOLEAN   ┆ 450000 DC  ┆ $.MTS PMS │
│        ┆            ┆          ┆            ┆   ┆           ┆           ┆ DISTRIBUTI ┆ KEB6      │
│        ┆            ┆          ┆            ┆   ┆           ┆           ┆ ON         ┆ Power Dis │
│        ┆            ┆          ┆            ┆   ┆           ┆           ┆            ┆ tribut…   │
│ KEB6   ┆ MA24V      ┆ null     ┆ Bool       ┆ … ┆ null      ┆ BOOLEAN   ┆ 450000 DC  ┆ $.MTS PMS │
│        ┆            ┆          ┆            ┆   ┆           ┆           ┆ DISTRIBUTI ┆ KEB6      │
│        ┆            ┆          ┆            ┆   ┆           ┆           ┆ ON         ┆ Power Dis │
│        ┆            ┆          ┆            ┆   ┆           ┆           ┆            ┆ tribut…   │
│ KEB6   ┆ PA0V       ┆ null     ┆ Bool       ┆ … ┆ null      ┆ BOOLEAN   ┆ 450000 DC  ┆ $.MTS PMS │
│        ┆            ┆          ┆            ┆   ┆           ┆           ┆ DISTRIBUTI ┆ KEB6      │
│        ┆            ┆          ┆            ┆   ┆           ┆           ┆ ON         ┆ Power Dis │
│        ┆            ┆          ┆            ┆   ┆           ┆           ┆            ┆ tribut…   │
│ …      ┆ …          ┆ …        ┆ …          ┆ … ┆ …         ┆ …         ┆ …          ┆ …         │
│ KEB9   ┆ System_5_4 ┆ null     ┆ Bool       ┆ … ┆ null      ┆ BOOLEAN   ┆ 450000     ┆ $.System_ │
│        ┆ 6_4_Cell_T ┆          ┆            ┆   ┆           ┆           ┆ MAIN POWER ┆ 5.46.4_Ce │
│        ┆ emperature ┆          ┆            ┆   ┆           ┆           ┆ STORAGE    ┆ ll_Temper │
│        ┆ …          ┆          ┆            ┆   ┆           ┆           ┆            ┆ atu…      │
│ KEB9   ┆ System_5_4 ┆ null     ┆ Bool       ┆ … ┆ null      ┆ BOOLEAN   ┆ 450000     ┆ $.System_ │
│        ┆ 6_4_Cell_T ┆          ┆            ┆   ┆           ┆           ┆ MAIN POWER ┆ 5.46.4_Ce │
│        ┆ emperature ┆          ┆            ┆   ┆           ┆           ┆ STORAGE    ┆ ll_Temper │
│        ┆ …          ┆          ┆            ┆   ┆           ┆           ┆            ┆ atu…      │
│ KEB9   ┆ System_5_4 ┆ null     ┆ Bool       ┆ … ┆ null      ┆ BOOLEAN   ┆ 450000     ┆ $.System_ │
│        ┆ 6_4_Cell_T ┆          ┆            ┆   ┆           ┆           ┆ MAIN POWER ┆ 5.46.4_Ce │
│        ┆ emperature ┆          ┆            ┆   ┆           ┆           ┆ STORAGE    ┆ ll_Temper │
│        ┆ …          ┆          ┆            ┆   ┆           ┆           ┆            ┆ atu…      │
│ KEB9   ┆ System_5_4 ┆ null     ┆ Bool       ┆ … ┆ null      ┆ BOOLEAN   ┆ 450000     ┆ $.System_ │
│        ┆ 6_4_Cell_T ┆          ┆            ┆   ┆           ┆           ┆ MAIN POWER ┆ 5.46.4_Ce │
│        ┆ emperature ┆          ┆            ┆   ┆           ┆           ┆ STORAGE    ┆ ll_Temper │
│        ┆ …          ┆          ┆            ┆   ┆           ┆           ┆            ┆ atu…      │
│ KEB9   ┆ System_5_4 ┆ null     ┆ Bool       ┆ … ┆ null      ┆ BOOLEAN   ┆ 450000     ┆ $.System_ │
│        ┆ 6_4_Cell_T ┆          ┆            ┆   ┆           ┆           ┆ MAIN POWER ┆ 5.46.4_Ce │
│        ┆ emperature ┆          ┆            ┆   ┆           ┆           ┆ STORAGE    ┆ ll_Temper │
│        ┆ …          ┆          ┆            ┆   ┆           ┆           ┆            ┆ atu…      │
└────────┴────────────┴──────────┴────────────┴───┴───────────┴───────────┴────────────┴───────────┘

In [2]:
from pathlib import Path
from zero_data.io_list.readers.marpower import MarpowerReader

io_result = MarpowerReader().read_io_list(
    [Path("../io_lists/52422003_3210_AMCS IO-List R2.14.xlsx")]
)
df = io_result.io_list
df

/Users/floris/Library/Caches/pypoetry/virtualenvs/zero-data-9oE-VVSS-py3.13/lib/python3.13/site-packages/openpyxl/worksheet/_reader.py:329: UserWarning: Data Validation extension is not supported and will be removed
  warn(msg)

shape: (4_879, 13)
┌────────┬────────────┬──────────┬────────────┬───┬───────────┬───────────┬────────────┬───────────┐
│ device ┆ tag        ┆ yard_tag ┆ target_typ ┆ … ┆ precision ┆ data_type ┆ mqtt_topic ┆ mqtt_json │
│ ---    ┆ ---        ┆ ---      ┆ e          ┆   ┆ ---       ┆ ---       ┆ ---        ┆ _path     │
│ str    ┆ str        ┆ str      ┆ ---        ┆   ┆ null      ┆ str       ┆ str        ┆ ---       │
│        ┆            ┆          ┆ str        ┆   ┆           ┆           ┆            ┆ str       │
╞════════╪════════════╪══════════╪════════════╪═══╪═══════════╪═══════════╪════════════╪═══════════╡
│ KEB1   ┆ GFDEnabled ┆ null     ┆ Bool       ┆ … ┆ null      ┆ BOOLEAN   ┆ 450000     ┆ $.GFDEnab │
│        ┆            ┆          ┆            ┆   ┆           ┆           ┆ AMCS/PWR   ┆ led       │
│ KEB1   ┆ FieldVolta ┆ null     ┆ Bool       ┆ … ┆ null      ┆ BOOLEAN   ┆ 450000     ┆ $.FieldVo │
│        ┆ geAvailabl ┆          ┆            ┆   ┆           ┆           ┆ AMCS/PWR   ┆ ltageAvai │
│        ┆ e          ┆          ┆            ┆   ┆           ┆           ┆            ┆ lable     │
│ KEB1   ┆ PA24V      ┆ null     ┆ Bool       ┆ … ┆ null      ┆ BOOLEAN   ┆ 450000     ┆ $.PA24V   │
│        ┆            ┆          ┆            ┆   ┆           ┆           ┆ AMCS/PWR   ┆           │
│ KEB1   ┆ MA24V      ┆ null     ┆ Bool       ┆ … ┆ null      ┆ BOOLEAN   ┆ 450000     ┆ $.MA24V   │
│        ┆            ┆          ┆            ┆   ┆           ┆           ┆ AMCS/PWR   ┆           │
│ KEB1   ┆ PA0V       ┆ null     ┆ Bool       ┆ … ┆ null      ┆ BOOLEAN   ┆ 450000     ┆ $.PA0V    │
│        ┆            ┆          ┆            ┆   ┆           ┆           ┆ AMCS/PWR   ┆           │
│ …      ┆ …          ┆ …        ┆ …          ┆ … ┆ …         ┆ …         ┆ …          ┆ …         │
│ KEB1   ┆ CAM2aft_Pr ┆ null     ┆ String     ┆ … ┆ null      ┆ STRING    ┆ 450000 UND ┆ $.Preset3 │
│        ┆ eset3HmiCo ┆          ┆            ┆   ┆           ┆           ┆ ERWLIGHTS/ ┆ HmiColor  │
│        ┆ lor        ┆          ┆            ┆   ┆           ┆           ┆ CAM2aft    ┆           │
│ KEB1   ┆ CAM2aft_Pr ┆ null     ┆ String     ┆ … ┆ null      ┆ STRING    ┆ 450000 UND ┆ $.Preset4 │
│        ┆ eset4HmiCo ┆          ┆            ┆   ┆           ┆           ┆ ERWLIGHTS/ ┆ HmiColor  │
│        ┆ lor        ┆          ┆            ┆   ┆           ┆           ┆ CAM2aft    ┆           │
│ KEB1   ┆ CAM2aft_Pr ┆ null     ┆ String     ┆ … ┆ null      ┆ STRING    ┆ 450000 UND ┆ $.Preset5 │
│        ┆ eset5HmiCo ┆          ┆            ┆   ┆           ┆           ┆ ERWLIGHTS/ ┆ HmiColor  │
│        ┆ lor        ┆          ┆            ┆   ┆           ┆           ┆ CAM2aft    ┆           │
│ KEB1   ┆ CAM2aft_Pr ┆ null     ┆ String     ┆ … ┆ null      ┆ STRING    ┆ 450000 UND ┆ $.Preset6 │
│        ┆ eset6HmiCo ┆          ┆            ┆   ┆           ┆           ┆ ERWLIGHTS/ ┆ HmiColor  │
│        ┆ lor        ┆          ┆            ┆   ┆           ┆           ┆ CAM2aft    ┆           │
│ KEB1   ┆ CAM2aft_Cu ┆ null     ┆ String     ┆ … ┆ null      ┆ STRING    ┆ 450000 UND ┆ $.Current │
│        ┆ rrentHmiCo ┆          ┆            ┆   ┆           ┆           ┆ ERWLIGHTS/ ┆ HmiColor  │
│        ┆ lor        ┆          ┆            ┆   ┆           ┆           ┆ CAM2aft    ┆           │
└────────┴────────────┴──────────┴────────────┴───┴───────────┴───────────┴────────────┴───────────┘

## Nested Topics Analysis

In [7]:
from zero_data.io_list import IOResult


def analyse_nested(
    _io_result: IOResult, topic_prefix: str, expected_num_fields: int | None = None
):
    powertags = [t for t in io_result.topics if t.topic.startswith(topic_prefix)]
    all_fields = list(
        set([(field.name, field.data_type) for t in powertags for field in t.fields])
    )
    print(
        f"All fields in topic {topic_prefix}:\n {'\n'.join([f'\t{f[0]}: {f[1]}' for f in all_fields])}\n\n"
    )
    for t in powertags:
        if t.fields != all_fields and (
            expected_num_fields is None or len(t.fields) != expected_num_fields
        ):
            print(t.topic, len(t.fields))


# analyse_nested("marpower/power-tag", 15)
analyse_nested(io_result, "marpower/450000-firedetection/")

All fields in topic marpower/450000-firedetection/:
 	test: BOOLEAN
	POWERSUPPLYFAIL: BOOLEAN
	prealarm: BOOLEAN
	fault: BOOLEAN
	SERVICESUPPLYFAIL: BOOLEAN
	disabled: BOOLEAN
	OPEN: BOOLEAN
	alarm: BOOLEAN
	FAULT: BOOLEAN
	RELEASE: BOOLEAN
	EMERGENCYSUPPLYFAIL: BOOLEAN


marpower/450000-firedetection/fire_door 1
marpower/450000-firedetection/fire_201h59s 5
marpower/450000-firedetection/fire_201h46 5
marpower/450000-firedetection/fire_201h43 5
marpower/450000-firedetection/fire_201h44 5
marpower/450000-firedetection/fire_201h23s 5
marpower/450000-firedetection/fire_201h10s 5
marpower/450000-firedetection/fire_201h60s 5
marpower/450000-firedetection/fire_doors 1
marpower/450000-firedetection/fire_201h5s 5
marpower/450000-firedetection/fire_201h54s 5
marpower/450000-firedetection/fire_201h19s 5
marpower/450000-firedetection/fire_201h41s 5
marpower/450000-firedetection/fire_201h21s 5
marpower/450000-firedetection/fire_201h40 10
marpower/450000-firedetection/fire_201h42 5
marpower/450000-firedetection/fire_201h55s 5
marpower/450000-firedetection/fire_201h62 5
marpower/450000-firedetection/fire_201h1s 5
marpower/450000-firedetection/fire_201h22 5
marpower/450000-firedetection/fire_201h30s 5
marpower/450000-firedetection/fire_201h13 5
marpower/450000-firedetection/fire_201h26 5
marpower/450000-firedetection/fire_201h24 5
marpower/450000-firedetection/fire_201h37s 5
marpower/450000-firedetection/fire_201h6s 5
marpower/450000-firedetection/fire_201h63 15
marpower/450000-firedetection/fire_201h54 5
marpower/450000-firedetection/fire_201h57s 5
marpower/450000-firedetection/fire_201h33 5
marpower/450000-firedetection/fire_201h47 5
marpower/450000-firedetection/fire_auxiliary_system 2
marpower/450000-firedetection/fire_201h50 5
marpower/450000-firedetection/fire_201h18s 5
marpower/450000-firedetection/fire_201h4s 5
marpower/450000-firedetection/fire_201h5 5
marpower/450000-firedetection/fire_201h52s 5
marpower/450000-firedetection/fire_201h19 5
marpower/450000-firedetection/fire_201h30 5
marpower/450000-firedetection/fire_201h44s 5
marpower/450000-firedetection/fire_201h63s 5
marpower/450000-firedetection/fire_201h34 15
marpower/450000-firedetection/fire_201h64s 5
marpower/450000-firedetection/fire_201h51s 5
marpower/450000-firedetection/fire_201h37 5
marpower/450000-firedetection/fire_201h2s 5
marpower/450000-firedetection/fire_201h25s 5
marpower/450000-firedetection/fire_201h6 5
marpower/450000-firedetection/fire_201h51 5
marpower/450000-firedetection/fire_201h57 5
marpower/450000-firedetection/fire_201h56 5
marpower/450000-firedetection/fire_201h34s 5
marpower/450000-firedetection/fire_201h27 5
marpower/450000-firedetection/fire_201h2 5
marpower/450000-firedetection/fire_201h16s 5
marpower/450000-firedetection/fire_201h64 5
marpower/450000-firedetection/fire_201h8 5
marpower/450000-firedetection/fire_201h50s 5
marpower/450000-firedetection/fire_201h28 5
marpower/450000-firedetection/fire_201h62s 5
marpower/450000-firedetection/fire_201h46s 5
marpower/450000-firedetection/fire_201h43s 5
marpower/450000-firedetection/fire_201h3 5
marpower/450000-firedetection/fire_201h12 5
marpower/450000-firedetection/fire_detect 1
marpower/450000-firedetection/fire_201h39 5
marpower/450000-firedetection/fire_201h45 5
marpower/450000-firedetection/fire_201h61s 5
marpower/450000-firedetection/fire_201h8s 5
marpower/450000-firedetection/fire_201h52 5
marpower/450000-firedetection/fire_201h60 10
marpower/450000-firedetection/fire_201h28s 5
marpower/450000-firedetection/fire_201h17 5
marpower/450000-firedetection/fire_201h27s 5
marpower/450000-firedetection/fire_201h15s 5
marpower/450000-firedetection/fire_201h7s 5
marpower/450000-firedetection/fire_201h13s 5
marpower/450000-firedetection/fire_201h26s 5
marpower/450000-firedetection/fire_201h48s 5
marpower/450000-firedetection/fire_201h1 5
marpower/450000-firedetection/fire_201h38s 5
marpower/450000-firedetection/fire_201h11s 5
marpower/450000-firedetection/fire_201h7 5
marpower/450000-firedetection/fire_201h55 5
marpower/450000-firedetection/fire_201h10 5
marpower/450000-firedetection/fire_201h22s 5
marpower/450000-firedetection/fire_201h3s 5
marpower/450000-firedetection/fire_201h17s 5
marpower/450000-firedetection/fire_201h53 10
marpower/450000-firedetection/fire_door_galley_keel 1
marpower/450000-firedetection/fire_201h20 5
marpower/450000-firedetection/fire_201h33s 5
marpower/450000-firedetection/fire_201h9 5
marpower/450000-firedetection/fire_201h47s 5
marpower/450000-firedetection/fire_201h53s 5
marpower/450000-firedetection/fire_201h18 5
marpower/450000-firedetection/fire_201h31 5
marpower/450000-firedetection/fire_201h21 5
marpower/450000-firedetection/fire_201h29 5
marpower/450000-firedetection/fire_201h36 5
marpower/450000-firedetection/fire_201h32 5
marpower/450000-firedetection/fire_201h23 5
marpower/450000-firedetection/fire_201h59 5
marpower/450000-firedetection/fire_201h4 5
marpower/450000-firedetection/fire_201h15 5
marpower/450000-firedetection/fire_201h14s 5
marpower/450000-firedetection/fire_201h31s 5
marpower/450000-firedetection/fire_201h14 5
marpower/450000-firedetection/fire_201h16 5
marpower/450000-firedetection/fire_201h9s 5
marpower/450000-firedetection/fire_201h38 5
marpower/450000-firedetection/fire_201h48 5
marpower/450000-firedetection/fire_201h61 5
marpower/450000-firedetection/fire_201h58 5
marpower/450000-firedetection/fire_201h12s 5
marpower/450000-firedetection/fire_201h41 5
marpower/450000-firedetection/fire_201h35 5
marpower/450000-firedetection/fire_201h11 5
marpower/450000-firedetection/fire_201h25 5

## System
System is a functional tag that is given by Vitters. The advantage of using this to group our topics is that the fields are grouped based on function.

In [14]:
df.group_by("system").len("number_of_fields").group_by("number_of_fields").len(
    "number_of_topics"
)

shape: (16, 2)
┌──────────────────┬──────────────────┐
│ number_of_fields ┆ number_of_topics │
│ ---              ┆ ---              │
│ u32              ┆ u32              │
╞══════════════════╪══════════════════╡
│ 42               ┆ 1                │
│ 1                ┆ 5                │
│ 20               ┆ 1                │
│ 54               ┆ 1                │
│ 17               ┆ 1                │
│ …                ┆ …                │
│ 33               ┆ 1                │
│ 14               ┆ 1                │
│ 2                ┆ 3                │
│ 38               ┆ 1                │
│ 24               ┆ 1                │
└──────────────────┴──────────────────┘

In [15]:
df.group_by("system").len("number_of_fields").sort("number_of_fields", descending=True)

shape: (24, 2)
┌────────────────────┬──────────────────┐
│ system             ┆ number_of_fields │
│ ---                ┆ ---              │
│ str                ┆ u32              │
╞════════════════════╪══════════════════╡
│ 4500 AMCS          ┆ 95               │
│ Navigation Lights  ┆ 80               │
│ 2500 FRESH WATER   ┆ 54               │
│ 3500 VENTILATION   ┆ 42               │
│ 0900 DOORS HATCHES ┆ 38               │
│ …                  ┆ …                │
│ AMCS - CTRL        ┆ 1                │
│ 2900 PNEUMATIC     ┆ 1                │
│ 2102 BILGE FIFI    ┆ 1                │
│ 7500 PASSERELLE    ┆ 1                │
│ 4500 FIREDETECTION ┆ 1                │
└────────────────────┴──────────────────┘

## Device - Module
This is a combination of the AMCS device and the PLC module it is connected to and has no functional meaning.

In [16]:
df.group_by("device", "module").len("number_of_fields").group_by(
    "number_of_fields"
).len("number_of_topics").sort("number_of_fields", descending=True)

shape: (9, 2)
┌──────────────────┬──────────────────┐
│ number_of_fields ┆ number_of_topics │
│ ---              ┆ ---              │
│ u32              ┆ u32              │
╞══════════════════╪══════════════════╡
│ 80               ┆ 1                │
│ 16               ┆ 2                │
│ 8                ┆ 25               │
│ 7                ┆ 2                │
│ 6                ┆ 6                │
│ 4                ┆ 22               │
│ 3                ┆ 1                │
│ 2                ┆ 8                │
│ 1                ┆ 2                │
└──────────────────┴──────────────────┘

In [17]:
df.group_by("device", "module").len("number_of_fields").sort(
    "number_of_fields", descending=True
)

shape: (69, 3)
┌───────────┬────────┬──────────────────┐
│ device    ┆ module ┆ number_of_fields │
│ ---       ┆ ---    ┆ ---              │
│ str       ┆ str    ┆ u32              │
╞═══════════╪════════╪══════════════════╡
│ NavLights ┆ null   ┆ 80               │
│ KEB1      ┆ DO61   ┆ 16               │
│ KEB1      ┆ DO60   ┆ 16               │
│ KEB1      ┆ DO00   ┆ 8                │
│ KEB1      ┆ DI29   ┆ 8                │
│ …         ┆ …      ┆ …                │
│ KEB2      ┆ AO60   ┆ 2                │
│ KEB1      ┆ AI31   ┆ 2                │
│ KEB1      ┆ AO60   ┆ 2                │
│ KEB2      ┆ DI30   ┆ 1                │
│ KEB2      ┆ AI29   ┆ 1                │
└───────────┴────────┴──────────────────┘

# IO List proposition
We would prefer that the data is grouped by function in to topics. Having large topics includes more data duplication. So our preference would go to smaller topics. To make choices we have come up with a few principles:
- Group by "System" (2500 TECHWATER, 4500 AMCS, 3400 SEWAGE, Etc)
- Split if there is a difference in frequency of change: Alarms and (high frequency) sensors
- For 'large' topics (number of fields > ~30) see if splitting is possible.
- If there is a large number of fields that are similar in function, having larger topics is acceptable.